// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTrackingSoftware.Server.Controllers;

#nullable disable

namespace ProjectTrackingSoftware.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118013142_AddProjectsAndKanban")]
    partial class AddProjectsAndKanban
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.Kanban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Kanbans");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.KanbanColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KanbanId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KanbanId", "Position")
                        .HasDatabaseName("idx_kanbancolumn_kanban_pos");

                    b.ToTable("KanbanColumn", (string)null);
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.KanbanTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ColumnId", "Position")
                        .HasDatabaseName("idx_kanbanticket_column_pos");

                    b.ToTable("KanbanTicket", (string)null);
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_projectmember_user");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.Kanban", b =>
                {
                    b.HasOne("ProjectTrackingSoftware.Server.Entities.Project", "Project")
                        .WithOne("Kanban")
                        .HasForeignKey("ProjectTrackingSoftware.Server.Entities.Kanban", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.KanbanColumn", b =>
                {
                    b.HasOne("ProjectTrackingSoftware.Server.Entities.Kanban", "Kanban")
                        .WithMany("KanbanColumns")
                        .HasForeignKey("KanbanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kanban");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.KanbanTicket", b =>
                {
                    b.HasOne("ProjectTrackingSoftware.Server.Entities.KanbanColumn", "Column")
                        .WithMany("KanbanTickets")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTrackingSoftware.Server.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.Project", b =>
                {
                    b.HasOne("ProjectTrackingSoftware.Server.Entities.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.ProjectMember", b =>
                {
                    b.HasOne("ProjectTrackingSoftware.Server.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTrackingSoftware.Server.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.User", b =>
                {
                    b.HasOne("ProjectTrackingSoftware.Server.Entities.Project", null)
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.Kanban", b =>
                {
                    b.Navigation("KanbanColumns");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.KanbanColumn", b =>
                {
                    b.Navigation("KanbanTickets");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.Project", b =>
                {
                    b.Navigation("Kanban")
                        .IsRequired();

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("ProjectTrackingSoftware.Server.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
